# Generated by Django 3.2.23 on 2023-12-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SweetSpot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
