# Generated by Django 3.2.23 on 2023-12-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetSpot', '0003_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.AlterModelOptions(
            name='dinnerreservation',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='dinnerreservation',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dinnerreservation',
            name='special_request',
            field=models.TextField(blank=True),
        ),
    ]
